#!/bin/sh

case "$cc" in
  *gcc*)
    opts="-Wno-implicit";
    ;;
  *)
    opts=""
    ;;
esac

if test "$verbose" = yes; then
echo "runtest: $cc $opts -o tst $* $cclibs" >&2
$cc $opts -o tst $* $cclibs || exit 100
else
$cc $opts -o tst $* $cclibs 2> /dev/null || exit 100
fi
exec ./tst
